apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "third.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "third.labels" . | nindent 4 }}
data:
  first_name: {{ .Values.first.name | quote }}
  first_port: {{ .Values.first.port | quote }}
  second_name: {{ .Values.second.name | quote }}
  second_port: {{ .Values.second.port | quote }}
