apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "third.fullname" . }}
  labels:
    {{- include "third.labels" . | nindent 4 }}
data:
  first_name: {{ .Values.first.name }}
  first_port: {{ .Values.first.port }}
  second_name: {{ .Values.second.name }}
  second_port: {{ .Values.second.port }}
